myapp/urls.py
from django.http import HttpResponse
from django.urls import path
from myapp.views import index,add_person,get_city

app_name="myapp"
urlpatterns = [
    path('', index, name='index'),
    path('person/', add_person, name='add-person'),
    path('get-city/<id>', get_city, name='get-city'),

]

webform/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import  include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('myapp.urls')),
]

myapp/models.py
from django.db import models

app_name="myapp"

# Create your models here.
class Country(models.Model):
    name=models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.name

class City(models.Model):
    name=models.CharField(max_length=50)
    country=models.ForeignKey(Country,on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name

class Person(models.Model):
    name=models.CharField(max_length=50)
    phone=models.IntegerField()
    address=models.CharField(max_length=80)
    country=models.ForeignKey(Country,on_delete=models.CASCADE, null=True)
    city=models.ForeignKey(City,on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return self.name 
    

myapp/forms.py
from django import forms

from .models import Person

app_name="myapp"
class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields=('name','phone', 'address', 'country', 'city')

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from myapp.models import City,Country,Person
from myapp.forms import PersonForm
from django.shortcuts import redirect

# Create your views here.

def index(request):
    country=Country.objects.all()
    context={
        'country':country,
    }
    #return HttpResponse("hey%s"%slug)
    return render(request, 'myapp/home.html', context)


def add_person(request):
    if request.method=="POST":
        form=PersonForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form=PersonForm()
        context={
            'form':form,
        }
        return render(request, 'myapp/person.html', context)
def get_city(request,id):
    opt2_html = ""
    try:
        country=Country.objects.get(pk = id)
        city = City.objects.filter(country_id = country.id)
        # make_models  = company.makemodel_set.all()
        for c in city:
            opt2_html += "<option value='"+str(c.id)+"'>"+c.name+"</option>"
            print(opt2_html) 
            context={
            'country':country,
            'city':city,
            }
        
    except:
        write_exception("Error in fetching options 2")
    return HttpResponse(opt2_html)
    # return render(request, 'myapp/home.html', context)

myapp/templates/myapp/home.html
{% extends "myapp/index.html" %} {% block contents %} {% csrf_token %} {% load static %}
<br> select dropdown<br>
<div>
    <a href="{% url 'myapp:add-person' %}" class="top-menu">Person</a>
</div>country
<div>
    <select id="selectbox1">
    <option>Select country</option>
    {% for c in country %}
    <option value="{{ c.id }}">{{c.name }}</option>
    {% endfor %}</select>
    <select id="selectbox2">city
    <option>Select country First</option>
</select></div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    $('#selectbox1').on("change", function() {
        $.get("get-city/" + $('#selectbox1').val(), function(data) {
            $("#selectbox2").html(data);
            console.log(data);
        }, "html")
    });
    get - city0
</script> {% endblock contents %}

myapp/templates/myapp/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My web application</title>
</head>


<body>
    <div>


        {% block contents %} {% endblock contents %}

    </div>
</body>

</html>

myapp/templates/myapp/person.html
{% extends 'myapp/index.html' %} {% block contents %}
<h2>Add Person</h2>
<form method="POST" class="post-form">{% csrf_token %} {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
</form>
{% endblock contents %}